name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-api-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: DjangoをUbuntu-Serverに自動デプロイ
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd src/django-cd-sample
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart mysite
    
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NuxtプロジェクトをUbuntu-Serverに自動デプロイ
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd src/django-cd-sample
            git clone origin main
            cd frontend
            npm install --legacy-peer-deps
            npm run generate
            sudo rm -rf /var/www/mysite/frontend
            sudo cp -r ./dist /var/www/mysite/frontend
